---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/bundles/{id}/bundling_availability":
    get:
      summary: Get maximum possible bundles based on component stock in single bins
      tags:
      - Inventory Transformations
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        description: ID of the Bundle Product
        required: true
        schema:
          type: integer
      - name: warehouse_id
        in: query
        description: ID of the Warehouse to check
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '404':
          description: bundle not found
  "/api/v1/bundles/bundle_inventory":
    post:
      summary: Execute Bundling Transformation
      tags:
      - Inventory Transformations
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: failed transaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                bundle:
                  type: object
                  properties:
                    bundle_product_id:
                      type: integer
                    destination_location_id:
                      type: integer
                    quantity_to_create:
                      type: integer
                    components:
                      type: array
                      items:
                        type: object
                        properties:
                          product_id:
                            type: integer
                          inventory_location_id:
                            type: integer
                          quantity_per_bundle:
                            type: integer
                        required:
                        - product_id
                        - inventory_location_id
                        - quantity_per_bundle
                  required:
                  - bundle_product_id
                  - destination_location_id
                  - quantity_to_create
                  - components
              required:
              - bundle
  "/api/v1/inventory_locations/by_warehouse":
    get:
      summary: Get inventory locations by warehouse
      tags:
      - InventoryLocations
      security:
      - bearerAuth: []
      parameters:
      - name: warehouse_id
        in: query
        description: Warehouse ID
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '400':
          description: bad request
  "/api/v1/inventory_locations/{id}":
    get:
      summary: Show inventory details for a location
      tags:
      - InventoryLocations
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        description: Inventory Location ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '404':
          description: not found
  "/api/v1/inventory_locations/{id}/history":
    get:
      summary: Get inventory history for a location
      tags:
      - InventoryLocations
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        description: Inventory Location ID
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '404':
          description: not found
  "/api/v1/inventory_locations/available_capacity":
    get:
      summary: Get available capacity for all inventory locations
      tags:
      - InventoryLocations
      security:
      - bearerAuth: []
      parameters:
      - name: warehouse_id
        in: query
        description: Warehouse ID
        schema:
          type: integer
      responses:
        '200':
          description: successful
  "/api/v1/inventory_transfers/locations_to_transfer":
    get:
      summary: Get locations to transfer inventory to
      tags:
      - InventoryTransfers
      security:
      - bearerAuth: []
      parameters:
      - name: warehouse_id
        in: query
        description: Warehouse ID
        schema:
          type: integer
      responses:
        '200':
          description: successful
  "/api/v1/inventory_transfers/transfer_inventory":
    post:
      summary: Transfer inventory between locations
      tags:
      - InventoryTransfers
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                transfer_params:
                  type: object
                  properties:
                    source_location_id:
                      type: integer
                    destination_location_id:
                      type: integer
                    items:
                      type: object
                      additionalProperties:
                        type: object
                        properties:
                          quantity:
                            type: integer
                        required:
                        - quantity
                  required:
                  - source_location_id
                  - destination_location_id
                  - items
              required:
              - transfer_params
  "/api/v1/products":
    get:
      summary: List all products
      tags:
      - Products
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
    post:
      summary: Create a product
      tags:
      - Products
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product:
                  type: object
                  properties:
                    name:
                      type: string
                    brand:
                      type: string
                    price:
                      type: number
                  required:
                  - name
                  - brand
                  - price
              required:
              - product
  "/api/v1/products/{id}":
    get:
      summary: Show a product
      tags:
      - Products
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
        '404':
          description: not found
    patch:
      summary: Update a product
      tags:
      - Products
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        description: Product ID
        required: true
        schema:
          type: string
      responses:
        '200':
          description: updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product:
                  type: object
                  properties:
                    name:
                      type: string
                    brand:
                      type: string
                    price:
                      type: number
              required:
              - product
  "/api/v1/products/lookup":
    get:
      summary: Lookup a product by barcode
      tags:
      - Products
      security:
      - bearerAuth: []
      parameters:
      - name: barcode
        in: query
        description: Product Barcode
        schema:
          type: string
      responses:
        '200':
          description: successful
        '404':
          description: not found
  "/api/v1/receivings/receive_inventory":
    post:
      summary: Receive inventory
      tags:
      - Receiving
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                receiving:
                  type: object
                  properties:
                    product_id:
                      type: integer
                    location_id:
                      type: integer
                    quantity:
                      type: integer
                  required:
                  - product_id
                  - location_id
                  - quantity
              required:
              - receiving
  "/api/v1/signup":
    post:
      summary: Registers a new user
      tags:
      - Authentication
      parameters: []
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Validation error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                  required:
                  - name
                  - email
                  - password
                  - password_confirmation
              required:
              - user
  "/api/v1/login":
    post:
      summary: Logs in an existing user
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
              required:
              - email
              - password
  "/api/v1/unbundles/unbundle":
    post:
      summary: Unbundle a product into its components
      tags:
      - Inventory Transformations
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: insufficient inventory
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                unbundle:
                  type: object
                  properties:
                    bundle_product_id:
                      type: integer
                      description: ID of the bundle product
                    inventory_location_id:
                      type: integer
                      description: ID of the location/bin
                    quantity:
                      type: integer
                      description: Number of bundles to unpack
                  required:
                  - product_id
                  - inventory_location_id
                  - quantity
              required:
              - unbundle
  "/api/v1/warehouses":
    get:
      summary: List warehouses
      tags:
      - Warehouses
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '401':
          description: unauthorized
  "/api/v1/warehouses/{id}":
    parameters:
    - name: id
      in: path
      description: Warehouse ID
      required: true
      schema:
        type: integer
    get:
      summary: Show warehouse
      tags:
      - Warehouses
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
        '404':
          description: not found
        '401':
          description: unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
servers:
- url: http://localhost:4000
  description: Local server
